# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Moodle Auto Updater
        uses: actions/setup-python@v2
        with:
          architecture: x64
      - run:  | 
            python webscrape.py
            pip install --user twine
            python -m twine --help
            

  
